name: pharmaplay_client
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^2.1.0
  json_annotation: ^4.3.0
  json_serializable: ^6.0.0
  shared_preferences: ^2.0.9
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc: ^8.0.1
  build_runner: ^2.1.5
  equatable: ^2.0.3
  flutter_bloc: ^8.0.0
  flutter_lints: ^1.0.4
  flutter_spinkit: ^5.1.0
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  formz: ^0.4.1
  uuid: ^3.0.5

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
