name: pharmaplay_client
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.0.9
  auto_size_text:
  built_collection: ^5.0.0
  built_value: ^8.0.6
  cached_network_image: ^3.1.0
  chewie: ^1.0.0
  cloud_firestore: ^2.5.4
  cloud_functions: ^3.0.0
  dash_chat:
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.7
  firebase_storage: ^10.0.1
  flutter_barcode_scanner: ^2.0.0
  flutter_google_places: ^0.3.0
  font_awesome_flutter:
  google_fonts: ^2.1.0
  google_sign_in: ^4.5.9
  image_picker: ^0.8.2
  intl:
  json_path: ^0.2.1
  json_serializable: ^4.0.1
  mime_type: ^1.0.0
  page_transition:
  rxdart: ^0.26.0
  sign_in_with_apple: ^3.0.0
  smooth_page_indicator:
  timeago:
  url_launcher:
  video_player: ^2.1.10
  build_runner: ^2.0.6
  built_value_generator: ^8.0.4
  flutter_launcher_icons: ^0.9.1

flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/