import 'tafqeet_unit.dart';
import 'unit_code.dart';

List<TafqeetUnit> tafqeetPredefinedUnits = [
  TafqeetUnit(
      country: '',
      unit: 'أونصة',
      unitPlural: 'أونصات',
      unitPartDigits: 0,
      unitPart: '',
      unitPartPlural: '',
      unitGender: TafqeetGender.feminine,
      unitPartGender: TafqeetGender.feminine,
      unitCode: TafqeetUnitCode.ounce),
  TafqeetUnit(
      country: '',
      unit: 'كيلو متر',
      unitPlural: 'كيلو مترات',
      unitPartDigits: 3,
      unitPart: 'متر',
      unitPartPlural: 'مترات',
      unitGender: TafqeetGender.masculine,
      unitPartGender: TafqeetGender.masculine,
      unitCode: TafqeetUnitCode.kiloMetre),
  TafqeetUnit(
      country: '',
      unit: 'ساعة',
      unitPlural: 'ساعات',
      unitPartDigits: 2,
      unitPart: 'دقيقة',
      unitPartPlural: 'دقائق',
      unitGender: TafqeetGender.feminine,
      unitPartGender: TafqeetGender.feminine,
      unitCode: TafqeetUnitCode.hour),
  TafqeetUnit(
      country: '',
      unit: 'متر',
      unitPlural: 'أمتار',
      unitPartDigits: 2,
      unitPart: 'سنتميتر',
      unitPartPlural: 'سنتيمترات',
      unitGender: TafqeetGender.masculine,
      unitPartGender: TafqeetGender.masculine,
      unitCode: TafqeetUnitCode.metre),
  TafqeetUnit(
      country: 'أميريكي',
      unit: 'دولار',
      unitPlural: 'دولارات',
      unitPartDigits: 2,
      unitPart: 'سنت',
      unitPartPlural: 'سنتات',
      unitGender: TafqeetGender.masculine,
      unitPartGender: TafqeetGender.masculine,
      unitCode: TafqeetUnitCode.unitedStatesDollar),
  TafqeetUnit(
      country: 'سعودي',
      unit: 'ريال',
      unitPlural: 'ريالات',
      unitPartDigits: 2,
      unitPart: 'هللة',
      unitPartPlural: 'هللات',
      unitGender: TafqeetGender.masculine,
      unitPartGender: TafqeetGender.feminine,
      unitCode: TafqeetUnitCode.saudiArabianRiyal),
  TafqeetUnit(
      country: 'سورية',
      unit: 'ليرة',
      unitPlural: 'ليرات',
      unitPartDigits: 2,
      unitPart: 'قرش',
      unitPartPlural: 'قروش',
      unitGender: TafqeetGender.feminine,
      unitPartGender: TafqeetGender.masculine,
      unitCode: TafqeetUnitCode.syrianPound),
  TafqeetUnit(
      country: '',
      unit: 'قلم',
      unitPlural: 'أٌقلام',
      unitPartDigits: 2,
      unitPart: 'جزء',
      unitPartPlural: 'أجزاء',
      unitGender: TafqeetGender.masculine,
      unitPartGender: TafqeetGender.masculine,
      unitCode: TafqeetUnitCode.undefined),
  TafqeetUnit(
      country: 'كويتي',
      unit: 'دينار',
      unitPlural: 'دنانير',
      unitPartDigits: 3,
      unitPart: 'فلس',
      unitPartPlural: 'فلوس',
      unitGender: TafqeetGender.masculine,
      unitPartGender: TafqeetGender.masculine,
      unitCode: TafqeetUnitCode.kuwaitiDinar),
  TafqeetUnit(
      country: '',
      unit: 'كيلو غرام',
      unitPlural: 'كيلو غرامات',
      unitPartDigits: 3,
      unitPart: 'غرام',
      unitPartPlural: 'غرامات',
      unitGender: TafqeetGender.masculine,
      unitPartGender: TafqeetGender.masculine,
      unitCode: TafqeetUnitCode.kiloGram),
];
