import 'tafqeet_unit.dart';
import 'unit_code.dart';

List<TafqeetUnit> tafqeetPredefinedUnits = [
  TafqeetUnit(
      unitCode: TafqeetUnitCode.ounce,
      country: '',
      unit: 'أونصة',
      unitPlural: 'أونصات',
      unitMaxValue: 0,
      unitGender: TafqeetUnitGender.feminine,
      partialUnitCode: TafqeetUnitCode.none),
  TafqeetUnit(
      unitCode: TafqeetUnitCode.hour,
      country: '',
      unit: 'ساعة',
      unitPlural: 'ساعات',
      unitMaxValue: 0,
      unitGender: TafqeetUnitGender.feminine,
      partialUnitCode: TafqeetUnitCode.minute),
  TafqeetUnit(
      country: '',
      unit: 'دقيقة',
      unitPlural: 'دقائق',
      unitMaxValue: 60,
      unitGender: TafqeetUnitGender.feminine,
      unitCode: TafqeetUnitCode.minute,
      partialUnitCode: TafqeetUnitCode.second),
  TafqeetUnit(
    unitCode: TafqeetUnitCode.second,
    country: '',
    unit: 'ثانية',
    unitPlural: 'ثواني',
    unitMaxValue: 60,
    unitGender: TafqeetUnitGender.feminine,
    partialUnitCode: TafqeetUnitCode.millisecond,
  ),
  TafqeetUnit(
    unitCode: TafqeetUnitCode.millisecond,
    country: '',
    unit: 'ميللي ثانية',
    unitPlural: 'ميللي ثواني',
    unitMaxValue: 60,
    unitGender: TafqeetUnitGender.feminine,
    partialUnitCode: TafqeetUnitCode.none,
  ),
  TafqeetUnit(
    unitCode: TafqeetUnitCode.kiloMetre,
    country: '',
    unit: 'كيلو متر',
    unitPlural: 'كيلو مترات',
    unitMaxValue: 0,
    unitGender: TafqeetUnitGender.masculine,
    partialUnitCode: TafqeetUnitCode.metre,
  ),
  TafqeetUnit(
      unitCode: TafqeetUnitCode.metre,
      country: '',
      unit: 'متر',
      unitPlural: 'امتار',
      unitMaxValue: 1000,
      unitGender: TafqeetUnitGender.masculine,
      partialUnitCode: TafqeetUnitCode.centimeter),
  TafqeetUnit(
      unitCode: TafqeetUnitCode.centimeter,
      country: '',
      unit: 'سنتميتر',
      unitPlural: 'سنتيمترات',
      unitMaxValue: 100,
      unitGender: TafqeetUnitGender.masculine,
      partialUnitCode: TafqeetUnitCode.millimeter),
  TafqeetUnit(
      unitCode: TafqeetUnitCode.millimeter,
      country: '',
      unit: 'ميللي',
      unitPlural: 'ميلليات',
      unitMaxValue: 10,
      unitGender: TafqeetUnitGender.masculine,
      partialUnitCode: TafqeetUnitCode.none),
  TafqeetUnit(
    unitCode: TafqeetUnitCode.unitedStatesDollar,
    country: 'أميريكي',
    unit: 'دولار',
    unitPlural: 'دولارات',
    unitMaxValue: 0,
    unitGender: TafqeetUnitGender.masculine,
    partialUnitCode: TafqeetUnitCode.unitedStatesDollarPenny,
  ),
  TafqeetUnit(
      unitCode: TafqeetUnitCode.unitedStatesDollarPenny,
      country: 'أميريكي',
      unit: 'سنت',
      unitPlural: 'سنتات',
      unitMaxValue: 100,
      unitGender: TafqeetUnitGender.masculine,
      partialUnitCode: TafqeetUnitCode.none),
  TafqeetUnit(
      unitCode: TafqeetUnitCode.saudiArabianRiyal,
      country: 'سعودي',
      unit: 'ريال',
      unitPlural: 'ريالات',
      unitMaxValue: 0,
      unitGender: TafqeetUnitGender.masculine,
      partialUnitCode: TafqeetUnitCode.saudiArabianRiyalPenny),
  TafqeetUnit(
      unitCode: TafqeetUnitCode.saudiArabianRiyalPenny,
      country: 'سعودي',
      unit: 'هللة',
      unitPlural: 'هللات',
      unitMaxValue: 100,
      unitGender: TafqeetUnitGender.feminine,
      partialUnitCode: TafqeetUnitCode.none),
  TafqeetUnit(
      country: 'سورية',
      unit: 'ليرة',
      unitPlural: 'ليرات',
      unitMaxValue: 0,
      unitGender: TafqeetUnitGender.feminine,
      unitCode: TafqeetUnitCode.syrianPound,
      partialUnitCode: TafqeetUnitCode.syrianPoundPenny),
  TafqeetUnit(
      unitCode: TafqeetUnitCode.syrianPoundPenny,
      country: 'سورية',
      unit: 'قرش',
      unitPlural: 'قروش',
      unitMaxValue: 100,
      unitGender: TafqeetUnitGender.masculine,
      partialUnitCode: TafqeetUnitCode.none),
  TafqeetUnit(
    unitCode: TafqeetUnitCode.undefined,
    country: '',
    unit: 'قلم',
    unitPlural: 'أٌقلام',
    unitMaxValue: 0,
    unitGender: TafqeetUnitGender.masculine,
    partialUnitCode: TafqeetUnitCode.undefinedPart,
  ),
  TafqeetUnit(
      unitCode: TafqeetUnitCode.undefinedPart,
      country: '',
      unit: 'جزء',
      unitPlural: 'أجزاء',
      unitMaxValue: 0,
      unitGender: TafqeetUnitGender.masculine,
      partialUnitCode: TafqeetUnitCode.none),
  TafqeetUnit(
      unitCode: TafqeetUnitCode.kuwaitiDinar,
      country: 'كويتي',
      unit: 'دينار',
      unitPlural: 'دنانير',
      unitMaxValue: 0,
      unitGender: TafqeetUnitGender.masculine,
      partialUnitCode: TafqeetUnitCode.kuwaitiDinarPenny),
  TafqeetUnit(
      unitCode: TafqeetUnitCode.kuwaitiDinarPenny,
      country: 'كويتي',
      unit: 'فلس',
      unitPlural: 'فلوس',
      unitMaxValue: 1000,
      unitGender: TafqeetUnitGender.masculine,
      partialUnitCode: TafqeetUnitCode.none),
  TafqeetUnit(
    unitCode: TafqeetUnitCode.metricTon,
    country: '',
    unit: 'طن',
    unitPlural: 'أطنان',
    unitMaxValue: 0,
    unitGender: TafqeetUnitGender.masculine,
    partialUnitCode: TafqeetUnitCode.kiloGram,
  ),
  TafqeetUnit(
    unitCode: TafqeetUnitCode.kiloGram,
    country: '',
    unit: 'كيلو غرام',
    unitPlural: 'كيلو غرامات',
    unitMaxValue: 1000,
    unitGender: TafqeetUnitGender.masculine,
    partialUnitCode: TafqeetUnitCode.gram,
  ),
  TafqeetUnit(
      unitCode: TafqeetUnitCode.gram,
      country: '',
      unit: 'غرام',
      unitPlural: 'غرامات',
      unitMaxValue: 1000,
      unitGender: TafqeetUnitGender.masculine,
      partialUnitCode: TafqeetUnitCode.none),
];
