name: form_builder_phone_field
description: Field for international phone number input for flutter_form_builder package.
version: 1.0.0-beta.0
homepage: https://github.com/danvick/form_builder_phone_field

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: "^2.2.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.0.0-beta.0
  phone_number: ^0.12.0
  country_pickers: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
