name: example
description: Example project for form_builder_phone_field
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_form_builder: ^7.0.0
  form_builder_phone_field:
    path: ../
  form_builder_validators: ^7.0.0
  
dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
